server:
  port: 8083
 
spring:
  application:
    name: "User-Registration"
   
  jpa:
    hibernate:
      ddl-auto: update
    database: MYSQL
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/chatter
    username: root
    password: Akshat@123
    driver-class-name: com.mysql.jdbc.Driver